/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dgroomes;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ClientMainTest {
    @Test void appHasAGreeting() {
        ClientMain classUnderTest = new ClientMain();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
